print("vikash",end=" ")
print("How",end=" ")
print("are",end=" ")
print("you")
print("vishal",end=" ")
print("yes",end=" ")
print("I",end=" ")
print("am",end=" ")
print("fine")
print("      Thanks!")